[package]
name = "challenges1"
version = "0.1.0"
authors = ["Eduardo DiÌaz <ediaz@dcc8090.cl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
